Kan 27 d veloppement t vs
picasso-utc/ocktopus pull request #14
Opened 2023-11-23 15:09 UTC by noams0

Une V1 des fonctionnalités de base des TVs et de leur gestion (sans documentation)

2023-11-23 20:12 UTC, adrsimon reviewed
je mets juste ça la pr y penser : il va falloir merge main pour mettre à jour l'archi du projet, le laravel ne vis plus dans `project`mais directement à la racine

2023-11-29 16:54 UTC, adrsimon reviewed
très bon début bravo!! quelques remarques sur les traits et l'utilisation d'un enum pour la validation de donnée côté php

pense à bien merge main ! on va avoir des pb sinon au merge
sur ta branche :
```bash
git fetch
git merge origin/main
```

2023-11-29 16:54 UTC, adrsimon commented on project/app/Models/Link.php
> +    use HasFactory;
les traits sont à mettre en début de classe c'est mieux
```php
class Link extends Model {
    use HasFactory;
    //....
}
```

2023-11-29 16:54 UTC, adrsimon commented on project/app/Models/Media.php
> +        'activate',
imo `activated` serait plus approprié d'un point de vue sémantique mais c'est du nitpick

2023-11-29 16:54 UTC, adrsimon commented on project/app/Models/Tv.php
> +    use HasFactory;
trait mal placé

2023-11-29 16:54 UTC, adrsimon commented on project/app/Models/Media.php
> +        'media_type',
on aurait pu créer une classe d'enum avec les différents types de média acceptés, et caster le champ comme valeur de l'enum, cf ma PR sur l'admin system

2023-11-29 16:54 UTC, adrsimon commented on project/database/migrations/2023_11_05_103743_create_media_table.php
> +            $table->enum('media_type', ['Image', 'Video'])->default('Image');
l'enum sql est cool du coup à compléter avec l'enum côté php

2023-12-02 16:54 UTC, adrsimon reviewed
lgtm, juste à confirmer avec @geosaglio ce qu'il préfère pr les enums, comme ça on choisit une convention et on l'applique partour

2023-12-02 16:54 UTC, adrsimon commented on project/app/Enums/MediaType.php
> +    const Video = 'Video';
pq utiliser un enum spatie alors qu'en php 8 les enums natifs ont été instaurés ? ça marche bien mais c un peu couper du pain avec une scie sauteuse

2023-12-02 19:19 UTC, geosaglio commented on project/app/Enums/MediaType.php
> +    const Video = 'Video';
On pourrras regarder pour changer les enum et evité les dépendances qui peuvent être évité! :))

2023-12-02 19:23 UTC, geosaglio requested changes
C'est vrmt super dans la globalité! c'est claire et ca utilise une bonne structure et les outils proposé par laravel donc GG!
On vera ensemble dimanche soir pour les Enum et j'aurais le temps de vraiment me poser avec toi pour voir le pb de temps de changement des medias videos!
désolé si javais pas trp le temps avant ❤️

2023-12-07 17:07 UTC, closed without merging